version: "3.7"

volumes:
  mongo:

networks:
  public:
    driver: bridge
services:
  frontend:
    build:
      context: ..
      dockerfile: ./ranch-deployment/ranch-frontend.Dockerfile
    image: ranch-frontend
    ports:
      - 8080:8080
    volumes:
      - ../ranch-frontend/stores:/ranch-frontend/stores
      - ../ranch-frontend/components:/ranch-frontend/components
      - ../ranch-frontend/styles:/ranch-frontend/styles
      - ../ranch-frontend/pages:/ranch-frontend/pages
      - ../ranch-frontend/public:/ranch-frontend/public
      - ../ranch-frontend/.next:/ranch-frontend/.next
    networks:
      - public
  envoy:
    build:
      context: ..
      dockerfile: ./ranch-deployment/ranch-envoy.Dockerfile
    image: ranch-envoy
    restart: "no"
    ports:
      - 8081:8080
    networks:
      - public

  backend:
    build:
      context: ..
      dockerfile: ./ranch-deployment/ranch-backend.Dockerfile
    image: ranch-backend
    ports:
      - 8082:8080
    depends_on:
      - mongodb
    volumes:
      - ./.volumes/alpaca.cpp/ggml-alpaca-7b-q4.bin:/alpaca.cpp/ggml-alpaca-7b-q4.bin
      - ../ranch-backend/src:/ranch-backend/src
    networks:
      - public

  mongodb:
    image: mongo:4.4.17
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "8083:27017"
    volumes:
      - mongo:/data/db
    networks:
      - public
  
  # mongo-express:
  #   image: mongo-express
  #   restart: "no"
  #   ports:
  #     - 8084:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/?authSource=admin
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - public