# mongodb, prisma2, ../ranch-bakcned ../ranch-frontend
version: "3.7"

volumes:
  ranch-mongo:

services:
  mongodb:
    image: mongo:6
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 8082:27017
    volumes:
      - ranch-mongo:/data/db

  backend:
    build:
      context: ..
      dockerfile: ./ranch-deployment/ranch-backend.Dockerfile
    image: ranch-backend
    restart: "no"
    ports:
      - 8081:4000
    # depends_on:
    #   - mongodb
    volumes:
      - ./.volumes/alpaca.cpp/ggml-alpaca-7b-q4.bin:/alpaca.cpp/ggml-alpaca-7b-q4.bin

  frontend:
    build:
      context: ..
      dockerfile: ./ranch-deployment/ranch-frontend.Dockerfile
    image: ranch-frontend
    restart: "no"
    ports:
      - 8080:3000
    volumes:
      - ../ranch-frontend/src:/ranch-frontend/src

  envoy:
    build:
      context: ..
      dockerfile: ./ranch-deployment/ranch-envoy.Dockerfile
    image: ranch-envoy
    restart: "no"
    ports:
      - 8083:8080
